repos:
  - repo: local
    hooks:
      - id: xmllint
        name: Check XML formatting
        entry: xmllint --noout
        language: system
        files: \.xml$
        description: Validates XML files are well-formed using xmllint